In [43]:
import pandas as pd
from plotting import Candleplot
pd.set_option("display.max.columns", None)

df_ma_res = pd.read_pickle(f"../data/ma_res.pkl")
df_ma_trades = pd.read_pickle(f"../data/ma_trades.pkl")

In [10]:
df_ma_res.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 480 entries, 0 to 479
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   pair         480 non-null    object
 1   num_trades   480 non-null    int64
 2   total_gain   480 non-null    int64
 3   mean_gain    480 non-null    int64
 4   min_gain     480 non-null    int64
 5   max_gain     480 non-null    int64
 6   ma_l         480 non-null    object
 7   ma_s         480 non-null    object
 8   cross        480 non-null    object
 9   granularity  480 non-null    object
dtypes: int64(5), object(5)
memory usage: 37.6+ KB

In [11]:
df_ma_res.granularity.unique()

array(['H1', 'H4'], dtype=object)

In [13]:
df_ma_res_h1 = df_ma_res[df_ma_res.granularity == "H1"].copy()
df_ma_trades_h1 = df_ma_trades[df_ma_trades.granularity == "H1"].copy()

In [17]:
df_ma_res_h1.columns

Index(['pair', 'num_trades', 'total_gain', 'mean_gain', 'min_gain', 'max_gain',
       'ma_l', 'ma_s', 'cross', 'granularity'],
      dtype='object')

In [19]:
df_cross_summary = df_ma_res_h1[['pair', 'num_trades', 'total_gain','cross',]].copy()

In [20]:
df_cross_summary

        pair  num_trades  total_gain         cross
0    EUR_USD         208          51   MA_10_MA_20
1    EUR_USD         106          34   MA_10_MA_40
2    EUR_USD         106        -431   MA_20_MA_40
3    EUR_USD         111        -357   MA_30_MA_40
4    EUR_USD          76        -496   MA_10_MA_80
..       ...         ...         ...           ...
235  CAD_JPY          35         716  MA_40_MA_120
236  CAD_JPY          48         398  MA_10_MA_150
237  CAD_JPY          38         335  MA_20_MA_150
238  CAD_JPY          34         881  MA_30_MA_150
239  CAD_JPY          30         763  MA_40_MA_150

[240 rows x 4 columns]

In [23]:
df_cross_gr = df_cross_summary.groupby(by= "cross", as_index=False).sum(numeric_only=True)
df_cross_gr.sort_values(by="total_gain", ascending=False, inplace=True)

In [24]:
df_cross_gr

           cross  num_trades  total_gain
10  MA_30_MA_150         473        8494
1   MA_10_MA_150         747        6977
6   MA_20_MA_150         571        6951
13  MA_40_MA_120         503        6819
14  MA_40_MA_150         439        6593
9   MA_30_MA_120         560        6465
5   MA_20_MA_120         649        5353
0   MA_10_MA_120         840        3982
3    MA_10_MA_40        1721        2495
4    MA_10_MA_80        1090        2341
12   MA_30_MA_80         784        1998
11   MA_30_MA_40        1748        1989
8    MA_20_MA_80         858        1924
15   MA_40_MA_80         763        1292
7    MA_20_MA_40        1515         -97
2    MA_10_MA_20        3177       -1161

In [34]:
total_pairs = len(df_ma_res_h1.pair.unique())

In [27]:
temp = df_ma_res_h1[df_ma_res_h1.cross == "MA_10_MA_40"]

In [30]:
temp[temp.total_gain > 0].shape[0]

9

In [35]:
for c in df_ma_res_h1.cross.unique():
    temp = df_ma_res_h1[df_ma_res_h1.cross == c]
    pg = temp[temp.total_gain > 0].shape[0]
    print(f"{c} pg:{pg} perc gain:{(pg / total_pairs) * 100:.0f}%")

MA_10_MA_20 pg:9 perc gain:60%
MA_10_MA_40 pg:9 perc gain:60%
MA_20_MA_40 pg:6 perc gain:40%
MA_30_MA_40 pg:8 perc gain:53%
MA_10_MA_80 pg:9 perc gain:60%
MA_20_MA_80 pg:7 perc gain:47%
MA_30_MA_80 pg:10 perc gain:67%
MA_40_MA_80 pg:8 perc gain:53%
MA_10_MA_120 pg:13 perc gain:87%
MA_20_MA_120 pg:8 perc gain:53%
MA_30_MA_120 pg:11 perc gain:73%
MA_40_MA_120 pg:12 perc gain:80%
MA_10_MA_150 pg:10 perc gain:67%
MA_20_MA_150 pg:10 perc gain:67%
MA_30_MA_150 pg:12 perc gain:80%
MA_40_MA_150 pg:11 perc gain:73%

In [36]:
cross = "MA_10_MA_20"
df_MA_10_MA_20 = df_ma_res_h1[df_ma_res_h1.cross == cross].copy()
df_MA_10_MA_20.sort_values(by="total_gain", ascending=False, inplace=True)

In [37]:
df_MA_10_MA_20

,pair,num_trades,total_gain,mean_gain,min_gain,max_gain,ma_l,ma_s,cross,granularity
80,USD_JPY,196,1112,5,-210,523,MA_20,MA_10,MA_10_MA_20,H1
224,CAD_JPY,203,583,2,-143,334,MA_20,MA_10,MA_10_MA_20,H1
64,EUR_CAD,215,373,1,-66,177,MA_20,MA_10,MA_10_MA_20,H1
160,GBP_CAD,211,324,1,-159,279,MA_20,MA_10,MA_10_MA_20,H1
176,AUD_USD,219,209,0,-61,187,MA_20,MA_10,MA_10_MA_20,H1
208,AUD_CAD,211,198,0,-58,164,MA_20,MA_10,MA_10_MA_20,H1
192,AUD_JPY,203,148,0,-160,450,MA_20,MA_10,MA_10_MA_20,H1
48,EUR_AUD,207,125,0,-111,203,MA_20,MA_10,MA_10_MA_20,H1
0,EUR_USD,208,51,0,-131,157,MA_20,MA_10,MA_10_MA_20,H1
16,EUR_GBP,225,-267,-1,-60,119,MA_20,MA_10,MA_10_MA_20,H1
96,USD_CAD,224,-282,-1,-84,258,MA_20,MA_10,MA_10_MA_20,H1
128,GBP_JPY,207,-356,-1,-323,1250,MA_20,MA_10,MA_10_MA_20,H1
144,GBP_AUD,225,-700,-3,-195,332,MA_20,MA_10,MA_10_MA_20,H1
112,GBP_USD,210,-908,-4,-123,171,MA_20,MA_10,MA_10_MA_20,H1
32,EUR_JPY,213,-1771,-8,-222,374,MA_20,MA_10,MA_10_MA_20,H1

In [38]:
df_gains = df_ma_trades_h1[(df_ma_trades_h1.cross==cross)&
                           (df_ma_trades_h1.pair=="CAD_JPY")].copy()

In [40]:
df_gains

,time,volume,mid_o,mid_h,mid_l,mid_c,bid_o,bid_h,bid_l,bid_c,ask_o,ask_h,ask_l,ask_c,MA_40,MA_10,MA_80,MA_20,MA_150,MA_120,MA_30,DELTA,DELTA_PREV,TRADE,DIFF,GAIN,granularity,pair,GAIN_C,ma_l,ma_s,cross
15341,2024-03-27 23:00:00+00:00,1747,111.402,111.432,111.344,111.364,111.391,111.420,111.334,111.355,111.414,111.443,111.353,111.374,111.479600,111.3976,111.419962,111.39400,111.572320,111.568117,111.444633,0.00360,-0.00650,1,-0.021,-2.1,H1,CAD_JPY,-2.1,MA_20,MA_10,MA_10_MA_20
15342,2024-03-28 10:00:00+00:00,2332,111.266,111.368,111.258,111.343,111.256,111.358,111.248,111.334,111.276,111.378,111.268,111.352,111.432000,111.4075,111.442988,111.41275,111.578927,111.517408,111.395233,-0.00525,0.01120,-1,0.453,-45.3,H1,CAD_JPY,-47.4,MA_20,MA_10,MA_10_MA_20
15343,2024-03-28 16:00:00+00:00,3187,111.843,111.852,111.707,111.796,111.834,111.843,111.697,111.786,111.852,111.862,111.717,111.805,111.444000,111.4907,111.467862,111.46920,111.582547,111.496850,111.425500,0.02150,-0.00020,1,-0.102,-10.2,H1,CAD_JPY,-57.6,MA_20,MA_10,MA_10_MA_20
15344,2024-03-29 08:00:00+00:00,1085,111.648,111.708,111.644,111.694,111.633,111.697,111.624,111.679,111.662,111.720,111.658,111.708,111.583675,111.7293,111.532500,111.75095,111.574627,111.477333,111.631467,-0.02165,0.00920,-1,0.069,-6.9,H1,CAD_JPY,-64.5,MA_20,MA_10,MA_10_MA_20
15345,2024-03-29 20:00:00+00:00,2147,111.744,111.812,111.729,111.763,111.711,111.784,111.657,111.675,111.777,111.867,111.758,111.851,111.660625,111.7112,111.565313,111.70410,111.549080,111.507833,111.742533,0.00710,-0.00465,1,0.071,7.1,H1,CAD_JPY,-57.4,MA_20,MA_10,MA_10_MA_20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15539,2024-11-01 09:00:00+00:00,5242,109.575,109.732,109.548,109.688,109.565,109.718,109.534,109.675,109.585,109.745,109.562,109.701,109.654825,109.4141,109.924013,109.34610,109.934107,109.977550,109.456667,0.06800,-0.01065,1,-0.526,-52.6,H1,CAD_JPY,687.2,MA_20,MA_10,MA_10_MA_20
15540,2024-11-04 01:00:00+00:00,7333,109.290,109.317,109.102,109.162,109.278,109.304,109.087,109.150,109.303,109.330,109.115,109.174,109.475575,109.5375,109.776850,109.54140,109.900740,109.949450,109.437767,-0.00390,0.05085,-1,0.298,-29.8,H1,CAD_JPY,657.4,MA_20,MA_10,MA_10_MA_20
15541,2024-11-04 18:00:00+00:00,4651,109.437,109.530,109.390,109.460,109.425,109.519,109.377,109.449,109.449,109.540,109.402,109.471,109.420200,109.2809,109.591663,109.27745,109.860193,109.809800,109.393467,0.00345,-0.01690,1,-0.036,-3.6,H1,CAD_JPY,653.8,MA_20,MA_10,MA_10_MA_20
15542,2024-11-05 19:00:00+00:00,4799,109.454,109.534,109.348,109.424,109.441,109.524,109.337,109.410,109.466,109.546,109.360,109.439,109.469350,109.5945,109.462812,109.60650,109.783573,109.657383,109.550033,-0.01200,0.00115,-1,0.708,-70.8,H1,CAD_JPY,583.0,MA_20,MA_10,MA_10_MA_20
15543,2024-11-06 00:00:00+00:00,18750,109.472,110.139,109.369,110.132,109.453,110.125,109.354,110.117,109.490,110.153,109.384,110.148,109.517575,109.6333,109.460313,109.63120,109.767133,109.636000,109.596467,0.00210,-0.03495,1,0.000,0.0,H1,CAD_JPY,583.0,MA_20,MA_10,MA_10_MA_20

In [45]:
cp = Candleplot(df_gains, candles=False)
cp.show_plot(line_traces=['GAIN_C'])

Candlestick figure created.

In [46]:
for curr in df_MA_10_MA_20[df_MA_10_MA_20.total_gain > 0].pair.unique():
    temp_gains = df_ma_trades_h1[(df_ma_trades_h1.cross==cross)&
                           (df_ma_trades_h1.pair==curr)].copy()
    print(curr, int(temp_gains.GAIN.sum()))
    cp = Candleplot(temp_gains, candles=False)
    cp.show_plot(line_traces=['GAIN_C'])

USD_JPY 1112
Candlestick figure created.

CAD_JPY 583
Candlestick figure created.

EUR_CAD 373
Candlestick figure created.

GBP_CAD 324
Candlestick figure created.

AUD_USD 209
Candlestick figure created.

AUD_CAD 198
Candlestick figure created.

AUD_JPY 148
Candlestick figure created.

EUR_AUD 125
Candlestick figure created.

EUR_USD 51
Candlestick figure created.

: