In [77]:
import sys
import os
sys.path.append(os.path.abspath("../"))
import pandas as pd
import plotly.graph_objects as go
import datetime as dt 
from plotting import Candleplot

In [78]:
from infrastructure.instrument_collection import instrumentCollection as ic

In [79]:
pair = "GBP_JPY"
granularity = "H4"
df = pd.read_pickle(f"../data/{pair}_{granularity}.pkl")
MA_list = [10 ,20 ,50 ,100 ,200]

In [80]:
df.columns

Index(['time', 'volume', 'mid_o', 'mid_h', 'mid_l', 'mid_c', 'bid_o', 'bid_h',
       'bid_l', 'bid_c', 'ask_o', 'ask_h', 'ask_l', 'ask_c'],
      dtype='object')

In [81]:
df_ma = df[['time', 'mid_o', 'mid_h', 'mid_l', 'mid_c']]

In [82]:
df_ma.head(10)

                       time    mid_o    mid_h    mid_l    mid_c
0 2022-04-14 01:00:00+00:00  164.616  164.686  164.370  164.586
1 2022-04-14 05:00:00+00:00  164.584  164.798  164.276  164.698
2 2022-04-14 09:00:00+00:00  164.698  164.777  164.358  164.400
3 2022-04-14 13:00:00+00:00  164.404  164.525  164.034  164.428
4 2022-04-14 17:00:00+00:00  164.430  164.779  164.392  164.655
5 2022-04-14 21:00:00+00:00  164.616  165.056  164.408  164.926
6 2022-04-15 01:00:00+00:00  164.924  165.282  164.770  165.184
7 2022-04-15 05:00:00+00:00  165.184  165.456  165.007  165.284
8 2022-04-15 09:00:00+00:00  165.284  165.363  165.102  165.260
9 2022-04-15 13:00:00+00:00  165.260  165.323  164.988  165.130

In [83]:
for ma in MA_list:
    df_ma[f'MA_{ma}'] = df_ma.mid_c.rolling(window=ma).mean()
df_ma.dropna(inplace=True)
df_ma.reset_index(inplace=True, drop=True)

C:\Users\amino\AppData\Local\Temp\ipykernel_27352\1967031491.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\amino\AppData\Local\Temp\ipykernel_27352\1967031491.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\amino\AppData\Local\Temp\ipykernel_27352\1967031491.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\amino\AppData\Local\Temp\ipykernel_27352\1967031491.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\amino\AppData\Local\Temp\ipykernel_27352\1967031491.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\amino\AppData\Local\Temp\ipykernel_27352\1967031491.py:3: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [84]:
df_plot = df_ma.iloc[:500]

In [85]:
df_plot.shape

(500, 10)

In [86]:
cp = Candleplot(df_plot)

Candlestick figure created.

In [87]:
traces = [f"MA_{x}" for x in MA_list]

In [88]:
cp.show_plot(line_traces=traces)

In [89]:
MA_S = "MA_50"
MA_L = "MA_200"
BUY = 1
SELL = -1
NONE = 0

In [90]:
df_an = df_ma[['time', 'mid_o', 'mid_h', 'mid_l', 'mid_c', MA_S, MA_L]]

In [91]:
df_an.head(30)

,time,mid_o,mid_h,mid_l,mid_c,MA_50,MA_200
0,2022-05-31 05:00:00+00:00,161.433,161.446,160.945,161.326,160.00048,161.841885
1,2022-05-31 09:00:00+00:00,161.326,161.654,161.053,161.614,160.04116,161.827025
2,2022-05-31 13:00:00+00:00,161.615,162.340,161.596,162.208,160.11652,161.814575
3,2022-05-31 17:00:00+00:00,162.208,162.362,162.010,162.180,160.19844,161.803475
4,2022-05-31 21:00:00+00:00,162.134,162.623,162.102,162.544,160.25960,161.794055
5,2022-06-01 01:00:00+00:00,162.545,162.766,162.389,162.586,160.32280,161.783710
6,2022-06-01 05:00:00+00:00,162.586,163.327,162.454,162.852,160.39480,161.773340
7,2022-06-01 09:00:00+00:00,162.850,163.092,162.686,162.776,160.46768,161.761300
8,2022-06-01 13:00:00+00:00,162.776,162.842,161.972,162.262,160.51400,161.746190
9,2022-06-01 17:00:00+00:00,162.260,162.691,162.214,162.480,160.57436,161.732290
10,2022-06-01 21:00:00+00:00,162.471,162.598,162.179,162.366,160.63624,161.718470
11,2022-06-02 01:00:00+00:00,162.366,162.432,162.133,162.378,160.68648,161.704560
12,2022-06-02 05:00:00+00:00,162.378,162.962,162.116,162.849,160.74392,161.693295
13,2022-06-02 09:00:00+00:00,162.848,162.910,162.591,162.766,160.80172,161.682555
14,2022-06-02 13:00:00+00:00,162.766,163.281,162.625,163.278,160.85996,161.674905
15,2022-06-02 17:00:00+00:00,163.278,163.425,163.148,163.352,160.91404,161.666925
16,2022-06-02 21:00:00+00:00,163.315,163.510,163.166,163.216,160.96470,161.657115
17,2022-06-03 01:00:00+00:00,163.216,163.384,163.065,163.226,161.00938,161.647005
18,2022-06-03 05:00:00+00:00,163.228,163.517,163.160,163.434,161.06778,161.636225
19,2022-06-03 09:00:00+00:00,163.433,163.678,163.322,163.582,161.13252,161.621250
20,2022-06-03 13:00:00+00:00,163.580,164.102,163.498,163.706,161.22420,161.603190
21,2022-06-03 17:00:00+00:00,163.704,163.746,163.327,163.382,161.31308,161.585015
22,2022-06-05 21:00:00+00:00,163.515,163.626,163.192,163.307,161.40610,161.564180
23,2022-06-06 01:00:00+00:00,163.306,163.328,162.912,163.326,161.49246,161.543060
24,2022-06-06 05:00:00+00:00,163.326,164.459,163.120,164.392,161.60064,161.523375
25,2022-06-06 09:00:00+00:00,164.394,164.438,163.915,164.230,161.70180,161.506555
26,2022-06-06 13:00:00+00:00,164.231,165.130,164.120,165.118,161.82174,161.495605
27,2022-06-06 17:00:00+00:00,165.118,165.472,165.092,165.254,161.95020,161.485645
28,2022-06-06 21:00:00+00:00,165.272,165.675,165.244,165.498,162.06520,161.478605
29,2022-06-07 01:00:00+00:00,165.498,166.145,165.498,166.076,162.18330,161.473445

In [92]:
df_an["DELTA"] = df_an.MA_50 - df_an.MA_200
df_an["DELTA_PREV"] = df_an.DELTA.shift(1)

C:\Users\amino\AppData\Local\Temp\ipykernel_27352\710530699.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\amino\AppData\Local\Temp\ipykernel_27352\710530699.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [93]:
def is_trade(row):
    if row.DELTA >= 0 and row.DELTA_PREV < 0:
        return BUY
    elif row.DELTA < 0 and row.DELTA_PREV >= 0:
        return SELL
    return NONE

In [94]:
df_an['TRADE'] = df_an.apply(is_trade, axis=1)

In [95]:
df_trades = df_an[df_an.TRADE != NONE].copy()

In [96]:
df_trades.head()

,time,mid_o,mid_h,mid_l,mid_c,MA_50,MA_200,DELTA,DELTA_PREV,TRADE
24,2022-06-06 05:00:00+00:00,163.326,164.459,163.120,164.392,161.60064,161.523375,0.077265,-0.050600,1
169,2022-07-08 09:00:00+00:00,161.999,163.584,161.901,163.529,163.93832,163.947075,-0.008755,0.057265,-1
236,2022-07-25 13:00:00+00:00,164.820,165.093,164.292,164.740,164.69278,164.651470,0.041310,-0.005960,1
263,2022-08-01 01:00:00+00:00,161.767,161.832,161.046,161.542,164.36944,164.414380,-0.044940,0.035605,-1
430,2022-09-07 21:00:00+00:00,165.785,166.325,165.761,166.083,162.52420,162.482745,0.041455,-0.039300,1

In [108]:
cp = Candleplot(df_an.iloc[200:280])
cp.show_plot(line_traces=[MA_S, MA_L])

Candlestick figure created.

In [98]:
ic.LoadInstruments("../data")

In [99]:
ic.instruments_dict[pair]

{'name': 'GBP_JPY', 'ins_type': 'CURRENCY', 'displayName': 'GBP/JPY', 'pipLocation': 0.01, 'tradeUnitsPrecision': 0, 'marginRate': 0.069}

In [100]:
ins_data = ic.instruments_dict[pair]

In [101]:
df_trades.head()

,time,mid_o,mid_h,mid_l,mid_c,MA_50,MA_200,DELTA,DELTA_PREV,TRADE
24,2022-06-06 05:00:00+00:00,163.326,164.459,163.120,164.392,161.60064,161.523375,0.077265,-0.050600,1
169,2022-07-08 09:00:00+00:00,161.999,163.584,161.901,163.529,163.93832,163.947075,-0.008755,0.057265,-1
236,2022-07-25 13:00:00+00:00,164.820,165.093,164.292,164.740,164.69278,164.651470,0.041310,-0.005960,1
263,2022-08-01 01:00:00+00:00,161.767,161.832,161.046,161.542,164.36944,164.414380,-0.044940,0.035605,-1
430,2022-09-07 21:00:00+00:00,165.785,166.325,165.761,166.083,162.52420,162.482745,0.041455,-0.039300,1

In [102]:
df_trades['DIFF'] = df_trades.mid_c.diff().shift(-1)
df_trades.fillna(0, inplace=True)

In [103]:
df_trades['GAIN'] = df_trades['DIFF'] / ins_data.pipLocation
df_trades['GAIN'] = df_trades['GAIN'] * df_trades['TRADE']

In [104]:
df_trades.GAIN.sum()

np.float64(-2719.899999999995)

In [105]:
df_trades['GAIN_C'] = df_trades['GAIN'].cumsum()

In [106]:
cp = Candleplot(df_trades, candles=False)
cp.show_plot(line_traces=['GAIN_C'])

Candlestick figure created.